services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bobi-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - bobi-auth:/app/src/auth
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    shm_size: '512mb'

volumes:
  bobi-auth:
